name: firestore_modeler
description: A DevTools extension that provides a visual editor to generate Firestore type-safe clients.
repository: https://github.com/pierremrtn/firestore_modeler
homepage: https://firestoremodeler.com
version: 0.2.0+1
screenshots:
  - description: 'A showcase of Firestore Modeler visual editor'
    path: doc/showcase.gif

topics:
  - firebase
  - firestore
  - odm
  - devtools
  - codegen

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore_odm: ^1.0.0-dev.88

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
